#!/bin/bash

nodemon --exec "eslint --cache --color -c /etc/nodeapp/eslintrc.json index.js **/*.json && babel-node --debug --presets /usr/local/lib/node_modules/babel-preset-es2017 --plugins /usr/local/lib/node_modules/babel-plugin-transform-es2015-modules-commonjs -- index.js"
